# Additional variables for KXStudio

# Set 'history' format to show more useful info
export HISTTIMEFORMAT="%d/%m/%y %T "

# For OSS Applications
export LD_PRELOAD=/usr/lib/libjackasyn.so.0${LD_PRELOAD:+:$LD_PRELOAD}

# SDL OSS -> JACK
export SDL_DRIVER=OSS

# Wine Real-Time Schedulling
#export WINE_RT=15
#export WINE_SVR_RT=10
