# Additional variables for KXStudio

# Set 'history' format to show more useful info
export HISTTIMEFORMAT="%d/%m/%y %T "

# Force KMix to use raw ALSA mode (disable PulseAudio)
export KMIX_PULSEAUDIO_DISABLE=1
