#!/bin/bash

# Trusty
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("kxstudio","trusty")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D trusty -v $VERSION "Trusty build"
debuild --no-lintian -S -sa

# Vivid
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("trusty","vivid")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D vivid -v $VERSION "Vivid build"
debuild --no-lintian -S -sa

# Wily
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("vivid","wily")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D wily -v $VERSION "Wily build"
debuild --no-lintian -S -sa

# Xenial
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("wily","xenial")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D xenial -v $VERSION "Xenial build"
debuild --no-lintian -S -sa

# Yakkety
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("xenial","yakkety")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D yakkety -v $VERSION "Yakkety build"
debuild --no-lintian -S -sa

# Zesty
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("yakkety","zesty")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D zesty -v $VERSION "Zesty build"
debuild --no-lintian -S -sa
