#!/bin/bash

# Quantal
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("precise","quantal")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D quantal -v $VERSION "Quantal build"
debuild --no-lintian -S -sa

# Raring
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("quantal","raring")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D raring -v $VERSION "Raring build"
debuild --no-lintian -S -sa

# Saucy
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("raring","saucy")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D saucy -v $VERSION "Saucy build"
debuild --no-lintian -S -sa
