#!/bin/bash

# Quantal
VERSION=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("precise","quantal")' | awk 'sub("\\\)","\n")' | head -n 1`
dch --force-distribution -D quantal -v $VERSION "Quantal build"
debuild -S -sa
