#!/bin/bash

# all dependencies:
# $ sudo apt-get install xserver-xephyr

init_screen () {
# Set up nested X server
Xephyr -keybd ephyr,,,xkbmodel=evdev -br -reset -screen 1280x720x24 -dpi 96 :2 &
sleep 1
}

start_screen_gnome2 () {
# set environment
export DISPLAY=:2.0

# start Gnome
gnome-panel &
nautilus

# wait for everything to close properly
sleep 2

# wait for ctrl+c here
export DISPLAY=:0
}

start_screen_kde4 () {
# set environment
export DISPLAY=:2.0
export KWIN_COMPOSE=N

# kill current desktop, only 1 instance allowed
killall plasma-desktop plasma-desktop.kde4

# start KDE
plasma-desktop
kwin

# wait for everything to close properly
sleep 2

# wait for ctrl+c here, restore desktop
export DISPLAY=:0
plasma-desktop
}

start_screen_kde5 () {
# set environment
sudo su - falk -c "$(pwd)/$(dirname $0)/xrec_1b.sh"
}

start_screen_xfce4 () {
# set environment
export DISPLAY=:2.0

# kill current panel, only 1 instance allowed
killall xfce4-panel

# start XFCE
xfce4-panel &
xfdesktop &
xfwm4

# wait for everything to close properly
sleep 2

# wait for ctrl+c here, restore desktop
export DISPLAY=:0
xfce4-panel &
}

case $1 in
  gnome2|-gnome2|--gnome2)
init_screen
start_screen_gnome
  ;;

  kde4|-kde4|--kde4)
init_screen
start_screen_kde4
  ;;

  kde5|-kde5|--kde5)
init_screen
start_screen_kde5
  ;;

  xfce4|-xfce4|--xfce4)
init_screen
start_screen_xfce4
  ;;

  *)
echo "usage: xrec_1 <DE>

DE can be:
    gnome2     Gnome2 session
    kde4       KDE4 session
    kde5       KDE5 session
    xfce4      XFCE4 session
"
  ;;

esac
