#!/bin/bash

DATE=`date +%Y%m%d`
TIME=`date +%Hh%M`
RATE=30
SAMPLE_RATE=`jack_samplerate`
FILENAME="$HOME/Screencasts/screencast_$DATE-$TIME"

export DISPLAY=:2.0

mkdir -p "$HOME/Screencasts/"

# Start screencast
ffmpeg_harvid \
  -fflags +genpts+igndts \
  -f x11grab -vsync 0 -r "$RATE" -s 1280x720 -i :2 -vcodec h264 \
  -f jack -ac 2 -r:a "$SAMPLE_RATE" -i screencast -acodec pcm_s16le -r:v "$RATE" -vsync 2 -async 1 -map 0:0,1,0 -map 1:0 \
  -preset ultrafast -qp 0 \
  "$FILENAME-lossless.mkv"

# Compress file
ffmpeg_harvid \
  -i "$FILENAME-lossless.mkv" -acodec mp3 -ab 160000 -vcodec h264 "$FILENAME-final.mkv"
