#!/bin/bash

# Script to automatically update git based debs and rebuild
# Please do the upload yourself, as this may take some time...

export LANG="C"
ALL=`ls`

# Run the action against all folders
for i in $ALL; do
  if [ -d $i/.git ]; then
    cd $i

    # Package version type
    DEBIAN=`cat debian/changelog | head -n 1 | awk '{printf$2}' | awk 'sub("\\\(","")' | awk 'sub("lucid","maverick")' | awk 'sub("\\\)","\n")' | head -n 1`
    DATE=`date +"20%y%m%d"`

    # Check if it has updates
    TEST_GIT=`git pull`
    if [ "$TEST_GIT" != "Already up-to-date." ]; then
        echo "New Git Available!!"
        echo "RUNNING AUTO-SCRIPT NOW!"
        VERSION="$DEBIAN""$DATE""-0~ppa1"
        dch -v $VERSION "New Git (scripted)"
        debuild -S -sa
    else
        echo "New Git NOT available..."
    fi

    cd ..
  fi
done
